"""add_is_guest_to_users

Revision ID: 480ff4d3679c
Revises: 69ddd74702a2
Create Date: 2026-05-02 23:14:15.266487

"""
from alembic import op
import sqlalchemy as sa


revision = '480ff4d3679c'
down_revision = '69ddd74702a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guest')
    # ### end Alembic commands ###
