"""add_scheduled_reminders_table

Revision ID: 69ddd74702a2
Revises: e14323ef11fb
Create Date: 2026-04-28 10:53:00.700783

"""
from alembic import op
import sqlalchemy as sa


revision = '69ddd74702a2'
down_revision = 'e14323ef11fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_reminders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reminders_send_at'), 'scheduled_reminders', ['send_at'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_user_id'), 'scheduled_reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_reminders_user_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_send_at'), table_name='scheduled_reminders')
    op.drop_table('scheduled_reminders')
    # ### end Alembic commands ###
