"""add_preferred_hour_and_scheduled_reminders

Revision ID: e14323ef11fb
Revises: fb978152f125
Create Date: 2026-04-28 10:49:54.189024

"""
from alembic import op
import sqlalchemy as sa


revision = 'e14323ef11fb'
down_revision = 'fb978152f125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_settings', sa.Column('preferred_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_settings', 'preferred_hour')
    # ### end Alembic commands ###
