"""add invite_split_mode to groups

Revision ID: e22fa2a915c9
Revises: f4d1c0b667c7
Create Date: 2026-04-19 22:04:44.745852

"""
from alembic import op
import sqlalchemy as sa


revision = 'e22fa2a915c9'
down_revision = 'f4d1c0b667c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_split_mode', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'invite_split_mode')
    # ### end Alembic commands ###
