"""add_group_close_fields

Revision ID: ead3d281b414
Revises: 83f923a30581
Create Date: 2026-04-10 02:35:08.557609

"""
from alembic import op
import sqlalchemy as sa


revision = 'ead3d281b414'
down_revision = '83f923a30581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_closed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('groups', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'closed_at')
    op.drop_column('groups', 'is_closed')
    # ### end Alembic commands ###
