"""add deferred_links table

Revision ID: f4d1c0b667c7
Revises: f1a2b3c4d5e6
Create Date: 2026-04-19 21:27:45.029912

"""
from alembic import op
import sqlalchemy as sa


revision = 'f4d1c0b667c7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deferred_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deferred_links_client_ip'), 'deferred_links', ['client_ip'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deferred_links_client_ip'), table_name='deferred_links')
    op.drop_table('deferred_links')
    # ### end Alembic commands ###
