"""add_periodic_settlement_tables

Revision ID: fb978152f125
Revises: e22fa2a915c9
Create Date: 2026-04-20 20:52:16.507928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fb978152f125'
down_revision = 'e22fa2a915c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balances_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_reports_group_id'), 'period_reports', ['group_id'], unique=False)
    op.create_table('period_debts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_paid_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['marked_paid_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['period_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_debts_report_id'), 'period_debts', ['report_id'], unique=False)
    op.add_column('expenses', sa.Column('period_report_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_expenses_period_report_id'), 'expenses', ['period_report_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'period_reports', ['period_report_id'], ['id'])
    op.add_column('groups', sa.Column('settlement_type', sa.String(length=10), nullable=False, server_default='none'))
    op.add_column('groups', sa.Column('settlement_period', sa.String(length=15), nullable=True))
    op.add_column('groups', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('next_settlement_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'next_settlement_date')
    op.drop_column('groups', 'current_period_start')
    op.drop_column('groups', 'settlement_period')
    op.drop_column('groups', 'settlement_type')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_period_report_id'), table_name='expenses')
    op.drop_column('expenses', 'period_report_id')
    op.drop_index(op.f('ix_period_debts_report_id'), table_name='period_debts')
    op.drop_table('period_debts')
    op.drop_index(op.f('ix_period_reports_group_id'), table_name='period_reports')
    op.drop_table('period_reports')
    # ### end Alembic commands ###
